### ISSUE TITLE
Incorrect article.text parsing (ricemedia.co)

### ISSUE THREAD

**Issue by fterh** [fterh/sneakpeek#2]
E.g. http://ricemedia.co/culture-events-sir-stamford-raffles-statue-disappeared/

Probably because the first chunk of text (before the image in the article):
1. Has 5 sentences < MIN_SENT_COUNT (default 7)
2. Has 113 words < MIN_WORD_COUNT (default 300)

**Comment by yleong** [comment]
I'll work on a custom handler.

**Comment by fterh** [comment]
Thanks @yleong :)

I experimented with MIN_WORD_COUNT and MIN_SENT_COUNT, I don't think they do what I thought they did: https://github.com/codelucas/newspaper/issues/662
