### ISSUE TITLE
Implement proper logging

### ISSUE THREAD

**Issue by yleong** [fterh/sneakpeek#21]
Right now the program only prints bare lines to stdout/stderr. We ought to use a proper logging library that adds timestamps, log levels and log rotations.

**Comment by fterh** [comment]
Yes for sure!

**Comment by fterh** [comment]
If v0.5.0-beta is stable (no more crashing), I think we can work towards a v1.0 version for logging and refactoring. All the major news sites are supported already, so I don't think v1.0 needs any new site support/features, other than logging and maybe PM2.

What do you guys think? @yleong @xlanor

**Comment by xlanor** [comment]
I'm fine with that.

I may look at setting up a graylog cluster for collaborators, if I have the time. Clearing up my finals.

**Comment by yleong** [comment]
Sure. I hope 0.5 does not crash anymore.

**Comment by fterh** [comment]
Looks good for now!

**Comment by xlanor** [comment]
Hi all,
I have managed to setup a graylog cluster for our internal usage.
Should we get a gitter or slack group going where we can converse easily?

**Comment by fterh** [comment]
@xlanor Sorry, finals period right now, will get back on this afterwards :)

**Comment by fterh** [comment]
I'm working on this using python's built-in logging library. I'll set it up to log to stdout, and we can make use of unix's redirection to either write to a logfile or set up a service to write it to a remote server (https://12factor.net/logs)
