### ISSUE TITLE
Program still crashes

### ISSUE THREAD

**Issue by fterh** [fterh/sneakpeek#25]
Here is the output copied off the end of `nohup.out`:

```
Sleeping
Starting main
Starting scan
Exception occurred while scanning
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/program.py", line 363, in run
    self.execute()
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/program.py", line 532, in execute
    executor.execute(*self.tasks)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/tasks.py", line 128, in __call__
    result = self.body(*args, **kwargs)
  File "/root/sneakpeek/tasks.py", line 7, in start
    c.run("ENV=prod python main.py")
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/context.py", line 101, in _run
    return runner.run(command, **kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 271, in run
    return self._run_body(command, **kwargs)
  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 365, in _run_body
    raise ThreadException(thread_exceptions)
invoke.exceptions.ThreadException:
Saw 1 exceptions within threads (OSError):


Thread args: {'kwargs': {'echo': None,
            'input_': <_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>,
            'output': <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>},
 'target': <bound method Runner.handle_stdin of <invoke.runners.Local object at 0x7fb67916bba8>>}

Traceback (most recent call last):

  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/util.py", line 233, in run
    super(ExceptionHandlingThread, self).run()

  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)

  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 641, in handle_stdin
    data = self.read_our_stdin(input_)

  File "/root/.local/share/virtualenvs/sneakpeek-osnio7yv/lib/python3.7/site-packages/invoke/runners.py", line 601, in read_our_stdin
    bytes_ = input_.read(bytes_to_read(input_))

OSError: [Errno 9] Bad file descriptor
```

**Comment by fterh** [comment]
This is happening very frequently now. I suspect it's to do with the read/write operations to the database file... perhaps now that the database file is growing larger in file size, read/write ops take longer and result in simultaneous accesses...?

Complete hunch. I'll look at this next week when I'm freer.

**Comment by fterh** [comment]
@yleong @xlanor I've been looking at main.py, and I'm wondering...

I'm catching the exception at line 24 `except Exception as e:`, as can be seen in the "log file": `Exception occurred while scanning`. Since the exception has been properly caught and handled, why does the Python process crash?

**Comment by yleong** [comment]
I'm not sure either, the exception handler at main.py:24 should have caught any exception in scan. I have just noticed that DatabaseManager.disconnect and the praw instantiation are not covered by the exception handler. Could the crashes be due to those lines? Can you share more crash logs if available? Maybe we can consider integrating with sentry.io so that we all can be notified of crashes and examine the exceptions. Or the graylog cluster would work too.

**Comment by xlanor** [comment]
Definitely, I'm currently tied down by my mods but I can assist. my graylog cluster is still up, should we move the discussion to slack/gitter?

**Comment by yleong** [comment]
Sure. Do we have one setup?

**Comment by fterh** [comment]
@yleong No worries, I read the documentation for the schedule library, and turns out it's that. When an exception bubbles up in a thread, it breaks the scheduler, so even though it was caught and handled in main.py, the scheduling thing breaks. The fix is documented here: https://schedule.readthedocs.io/en/stable/faq.html#what-if-my-task-throws-an-exception

@xlanor Yup, let's do that. You have my Telegram handle. No rush on the graylog cluster, I can push out a fix for the exception handling thing by the end of the week as perhaps v0.6.0-beta, and when graylog is up we can move to v1.0.

**Comment by changhuapeng** [comment]
@fterh If my understanding is correct, the Schedule library is used in this project to only scan for new submissions on the subreddit. Maybe you will want to replace the Schedule library with [PRAW's own method](https://praw.readthedocs.io/en/latest/tutorials/reply_bot.html) of monitoring new submissions if the scheduling part is really causing all the crashes.

**Comment by fterh** [comment]
> 
> 
> @fterh If my understanding is correct, the Schedule library is used in this project to only scan for new submissions on the subreddit. Maybe you will want to replace the Schedule library with [PRAW's own method](https://praw.readthedocs.io/en/latest/tutorials/reply_bot.html) of monitoring new submissions if the scheduling part is really causing all the crashes.

That's super cool, never knew about that! Will give it a read, thanks :)

**Comment by xlanor** [comment]
@changhuapeng @yleong , we are getting a slack channel up and going for anyone to join and discuss about sneakpeak.
[slack](https://join.slack.com/t/sneakpeakworkspace/shared_invite/enQtNjE1ODE1NjU0NzUzLTllYzA5YjkxNTgyMTY0MTlhMTZmMTU2MjU4MjUxYWVlYmI4NGQ3NTgyODEzNjljNTQ2YjgzNTIyYzViNmE4MmM)

Feel free to join!

**Comment by fterh** [comment]
@yleong I've pushed out 0.6.0-beta that uses Praw's mechanism for monitoring a subreddit. So far so good, will monitor for a bit and close this issue if it seems to work.

@xlanor for 1.0, since this issue is (hopefully) fixed already, I'm thinking we do logging and refactoring.

**Comment by xlanor** [comment]
@fterh 

Sounds good. I'm wondering if you'd also like to automate the deployment process via travis, which is free for open source repositories. Part of my job scope at work involves setting up a deployment pipeline and infrastructure.

Maybe you can open a travis integration to this repository first as preparation, once my holidays roll around next month I'll definetly be more involved

**Comment by fterh** [comment]
Sure. I'm familiar with Travis, but I'd thought that it was unnecessary because I originally envisioned this to be a minimal maintenance/development project in the sense that once the handlers are up and running, it shouldn't require any form of maintenance or development.

Looks like that plan got slightly thwarted :P But I agree that CI/CD is a good v1.0 milestone. Do you want to create a new issue for that? I'm closing this.
