### ISSUE TITLE
Detect and handle premium Straitstimes articles

### ISSUE THREAD

**Issue by fterh** [fterh/sneakpeek#6]

**Comment by yleong** [comment]
/u/jammy_buttons already has a bot capable of reposting premium ST articles. I'd suggest we detect and skip premium articles.

**Comment by fterh** [comment]
I thought (s)he was doing it manually? I'll check with him, if it's automated then yeah I'll close this issue.

**Comment by yleong** [comment]
I have opened #10 , please let me know what you think.

**Comment by fterh** [comment]
I'm a bit swamped at the moment. I'll get to that as soon as I can.

(Sorry, I didn't realize you created a PR 5 days ago - only saw it today!)
